name: Bot

on:
  workflow_dispatch:
    inputs:
      hours:
        description: "Bot Alive (Default 2 Hours)"
        required: true
        default: "2"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Inject Google Drive Cookies
        env:
          GDRIVE_COOKIES: ${{ secrets.GDRIVE_COOKIES }}
        run: |
          # Menyalin isi secret ke dalam file cookies.txt
          echo "$GDRIVE_COOKIES" > cookies.txt
          echo "Cookies injected successfully."

      - name: Start Telegram Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          PIXEL_TOKEN: ${{ secrets.PIXEL_TOKEN }}
        run: |
          HOURS=${{ github.event.inputs.hours }}
          echo "Starting bot for ${HOURS} hours..."
          
          # Eksekusi bot dengan batas waktu
          timeout ${HOURS}h python bot.py
          
          echo "Bot session timeout"